from reportlab.platypus import SimpleDocTemplate, Paragraph
from reportlab.lib.styles import getSampleStyleSheet
import os

def generate_pdf(result):

    if not os.path.exists("reports"):
        os.makedirs("reports")

    pdf_path = "reports/DriveSense_Report.pdf"

    doc = SimpleDocTemplate(pdf_path)

    styles = getSampleStyleSheet()

    story = []

    story.append(Paragraph("<b><font size=18>DriveSense AI Report</font></b>", styles["Title"]))
    story.append(Paragraph("<br/><br/>", styles["Normal"]))

    story.append(Paragraph(f"<b>Detected Sign:</b> {result['sign']}", styles["Normal"]))
    story.append(Paragraph(f"<b>Confidence:</b> {result['confidence']:.2f}%", styles["Normal"]))
    story.append(Paragraph(f"<b>Risk Level:</b> {result['risk']}", styles["Normal"]))
    story.append(Paragraph(f"<b>Driver Recommendation:</b> {result['action']}", styles["Normal"]))
    story.append(Paragraph(f"<b>Traffic Rule:</b> {result['rule']}", styles["Normal"]))

    story.append(Paragraph("<br/><br/>Generated by DriveSense AI", styles["Normal"]))

    doc.build(story)

    return pdf_path